####################################################################
# VSTS Build Configuration, Version 1.4
#
# (c)2021 superdev GmbH
####################################################################

name: $[format('{0}', variables['buildName'])]

pool:
  vmImage: 'windows-2019'

trigger:
  branches:
    include:
    - master
    - develop
    - release/*
    - feature/*
    - bugfix/*

  paths:
    exclude:
    - README.md
    - Images/*
    - Samples/*

variables:
  solution: 'PushNotifications.Server.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  majorVersion: 1
  minorVersion: 1
  patchVersion: 12
  version: $[format('{0}.{1}.{2}', variables.majorVersion, variables.minorVersion, variables.patchVersion)]
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    # Versioning: 1.0.0
    releaseOnNuget: true
    semVersion: $[format('{0}', variables.version)]
    buildName: $[format('{0}', variables.semVersion)]
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/release/') }}:
    # Versioning: 1.0.0-alpha.branch.123
    releaseOnNuget: true
    semVersionBase: $[format('{0}-alpha', variables.version)]
    semVersionRev: $[counter(variables.semVersionBase, 0)]
    semVersion: $[format('{0}.{1}', variables.semVersionBase, variables.semVersionRev)]
    buildName: $[format('Release - {0}', variables.semVersion)]
  ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/develop') }}:
    # Versioning: 1.0.0-develop.123
    releaseOnNuget: false
    semVersionBase: $[format('{0}-develop', variables.version)]
    semVersionRev: $[counter(variables.semVersionBase, 0)]
    semVersion: $[format('{0}.{1}', variables.semVersionBase, variables.semVersionRev)]
    buildName: $[format('Develop - {0}', variables.semVersion)]
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/') }}:
    # Versioning: 1.0.0-feature.branch.123
    releaseOnNuget: false
    semVersionBase: $[format('{0}-feature', variables.version)]
    semVersionRev: $[counter(variables.semVersionBase, 0)]
    semVersion: $[format('{0}.{1}', variables.semVersionBase, variables.semVersionRev)]
    buildName: $[format('Feature - {0}', variables.semVersion)]
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/pull/') }}: # Pull requests
    # Versioning: 1.0.0-pr.1.123
    releaseOnNuget: false
    semVersionBase: $[format('{0}-pr.{1}', variables.version, variables['System.PullRequest.PullRequestId'])]
    semVersionRev: $[counter(variables.semVersionBase, 0)]
    semVersion: $[format('{0}.{1}', variables.semVersionBase, variables.semVersionRev)]
    buildName: $[format('Pull Request - {0}', variables.semVersion)]

steps:
- task: Bash@3
  displayName: 'Print all variables'
  inputs:
    targetType: 'inline'
    script: 'env | sort'
   
- task: Assembly-Info-NetCore@2
  displayName: 'Update Assembly Info'
  inputs:
    Path: '$(Build.SourcesDirectory)'
    FileNames: |
      **/*.csproj
    InsertAttributes: true
    FileEncoding: 'auto'
    WriteBOM: false
    Product: 'PushNotifications.Server'
    Description: ''
    Company: 'superdev GmbH'
    Copyright: '(c) $(date:YYYY) superdev GmbH'
    VersionNumber: '$(Build.BuildNumber)'
    FileVersionNumber: '$(Build.BuildNumber)'
    InformationalVersion: '$(Build.BuildNumber)'
    PackageVersion: '$(Build.BuildNumber)'
    LogLevel: 'verbose'
    FailOnWarning: false
    DisableTelemetry: false'


- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 5.x'
  inputs:
    versionSpec: 5.x

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: '$(solution)'
    msbuildArgs: ''
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    
- task: DownloadSecureFile@1
  name: AuthKey_QWWBGJLG7F
  displayName: 'Download AuthKey'
  inputs:
    secureFile: 'AuthKey_QWWBGJLG7F.p8'
   
- task: DownloadSecureFile@1
  name: ServiceAccountKeyFile
  displayName: 'Download ServiceAccountKeyFile'
  inputs:
    secureFile: 'ServiceAccountKeyFile.json'
   
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Agent.TempDirectory)'
    Contents: |
      AuthKey_QWWBGJLG7F.p8
      ServiceAccountKeyFile.json
    TargetFolder: '$(System.DefaultWorkingDirectory)/Tests/PushNotifications.Server.Tests/Testdata'
    OverWrite: true
    flattenFolders: true

- task: DotNetCoreCLI@2
  displayName: 'Run UnitTests'
  inputs:
    command: test
    projects: '**/*.Tests.csproj'
    arguments: '--framework netcoreapp3.1'

- task: DotNetCoreCLI@2
  displayName: 'Pack PushNotifications.Server'
  inputs:
    command: pack
    packagesToPack: PushNotifications.Server/PushNotifications.Server.csproj
    versioningScheme: byEnvVar
    versionEnvVar: semVersion
    
- task: DotNetCoreCLI@2
  displayName: 'Pack PushNotifications.Server.AspNetCore'
  inputs:
    command: pack
    packagesToPack: PushNotifications.Server.AspNetCore/PushNotifications.Server.AspNetCore.csproj
    versioningScheme: byEnvVar
    versionEnvVar: semVersion

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'

    Contents: |
     **\bin\$(BuildConfiguration)\**
     **\bin\*.nupkg

    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
